# Generated by Django 5.2.5 on 2025-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thiet_bi', models.CharField(max_length=200)),
                ('nhom_thiet_bi', models.CharField(max_length=100)),
                ('ma_noi_bo', models.CharField(max_length=50, unique=True)),
                ('ma_nha_sx', models.CharField(max_length=100)),
                ('loai_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('so_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('nha_san_xuat', models.CharField(blank=True, max_length=100, null=True)),
                ('nha_cung_cap', models.CharField(blank=True, max_length=150, null=True)),
                ('nguoi_quan_ly', models.CharField(blank=True, max_length=100, null=True)),
                ('trang_thai_tai_san', models.CharField(blank=True, choices=[('dang_su_dung', 'Đang sử dụng'), ('dang_bao_tri', 'Đang bảo trì'), ('ngung_su_dung', 'Ngừng sử dụng')], max_length=20, null=True)),
                ('chuan_ga', models.CharField(blank=True, max_length=50, null=True)),
                ('loai_kep', models.CharField(blank=True, max_length=50, null=True)),
                ('chieu_dai_lam_viec', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duong_kinh_kep_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tu', models.CharField(blank=True, max_length=50, null=True)),
                ('ngan', models.CharField(blank=True, max_length=50, null=True)),
                ('may_uu_tien', models.CharField(blank=True, max_length=200, null=True)),
                ('ngay_nhap_kho', models.DateField(blank=True, null=True)),
                ('gia_tri_mua', models.BigIntegerField(blank=True, null=True)),
                ('chu_ky_kiem_tra', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_kiem_tra_gan_nhat', models.DateField(blank=True, null=True)),
                ('so_lan_ga_thao', models.IntegerField(blank=True, null=True)),
                ('danh_gia_gan_nhat', models.TextField(blank=True, null=True)),
                ('cv', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('dx', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mon', models.IntegerField(blank=True, null=True)),
                ('tan_suat', models.IntegerField(blank=True, null=True)),
                ('ld', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ket_luan_fuzzy', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
