# Generated by Django 5.2.5 on 2025-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0001_initial'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='ma_nhom_tuong_thich',
            field=models.CharField(blank=True, help_text='Nếu 2 holder có cùng mã này thì coi như tương thích / thay thế cho nhau', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='holder',
            name='tool_khuyen_dung',
            field=models.ManyToManyField(blank=True, help_text='Các tool tương thích & khuyên dùng với holder này', related_name='holders_khuyen_dung', to='tool.tool'),
        ),
    ]
