# Generated by Django 5.2.5 on 2025-11-21 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0002_tool_can_coolant_tool_diem_chat_luong_be_mat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('EXPORT', 'Xuất kho'), ('IMPORT', 'Nhập kho'), ('RETURN', 'Trả lại kho')], max_length=20)),
                ('so_luong', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ton_truoc', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ton_sau', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ma_du_an', models.CharField(blank=True, max_length=100)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nguoi_thuc_hien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.tool')),
            ],
        ),
    ]
