# Generated by Django 5.2.5 on 2025-11-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_muontra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltransaction',
            name='loai',
            field=models.CharField(choices=[('EXPORT', 'Xuất kho'), ('IMPORT', 'Nhập kho'), ('RETURN', 'Trả lại kho'), ('BAO_TRI_EXPORT', 'Xuất bảo trì'), ('BAO_TRI_RETURN', 'Trả bảo trì')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='so_luong',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='ton_sau',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='ton_truoc',
            field=models.PositiveIntegerField(),
        ),
    ]
