# Generated by Django 5.2.5 on 2025-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_muontra', '0002_alter_tooltransaction_loai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltransaction',
            name='loai',
            field=models.CharField(choices=[('EXPORT', 'Xuất kho'), ('IMPORT', 'Nhập kho'), ('RETURN', 'Trả lại kho')], max_length=20),
        ),
    ]
