# Generated by Django 5.2.5 on 2025-12-02 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_tool_can_coolant_tool_diem_chat_luong_be_mat_and_more'),
        ('tool_muontra', '0003_alter_tooltransaction_loai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltransaction',
            name='ly_do_fail',
            field=models.CharField(blank=True, default='', help_text='Lý do giao dịch thất bại do tủ gửi về.', max_length=255),
        ),
        migrations.AddField(
            model_name='tooltransaction',
            name='trang_thai',
            field=models.CharField(choices=[('PENDING', 'Đang chờ tủ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='tooltransaction',
            name='tx_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID giao dịch để map giữa Django và ESP32.', null=True),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='nguoi_thuc_hien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tool.tool'),
        ),
    ]
