# seed_tools_demo.py
# Tạo dữ liệu demo cho model Tool.
# Chạy:
#   python manage.py shell < seed_tools_demo.py

from datetime import date
from decimal import Decimal

# ĐỔI LẠI app name CHO ĐÚNG nếu khác
# VD: from danhsachcongcu.models import Tool
from tool.models import Tool

tools_data = [
    # ===== NHÓM KHOAN THÉP (DRILL + ISO P) – 3 tool gần giống nhau =====
    {
        "ten_tool": "Mũi khoan HSS Φ5.0",
        "ma_tool": "DRL-P-HSS-5.0",
        "nhom_tool": "Mũi khoan",
        "dong_tool": "Drill",
        "nha_san_xuat": "Totten",
        "ma_nha_sx": "HSS-5.0",
        "tieu_chuan": "DIN338",
        "model": "HSS Jobber",
        "vat_lieu_phu_hop": "C45, S50C",
        "ghi_chu": "",
        "duong_kinh": Decimal("5.00"),
        "chieu_dai_lam_viec": Decimal("52.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "1500 lỗ / tool",

        "loai_gia_cong": "DRILL",
        "duong_kinh_min": Decimal("4.80"),
        "duong_kinh_max": Decimal("5.10"),
        "ty_le_sau_lo_max": Decimal("5.0"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 15,
        "do_cung_max": 28,
        "may_phu_hop": "VMC 6000 rpm",
        "can_coolant": False,

        "ton_kho": 30,
        "muc_canh_bao": 10,
        "tu": "T1",
        "ngan": "NG1-01",
        "may_uu_tien": "Máy khoan bàn 01",
        "ngay_nhap_kho": date(2025, 1, 5),
        "gia_tri_mua": Decimal("12000"),

        "wear_max": 100,
        "nguong_thay": 80,
        "hrc_tham_chieu": 25,
        "che_do_cat_khuyen_nghi": "n=2500 rpm; f=0.12 mm/vòng; Vc≈40 m/phút",
        "ket_luan_fuzzy": "Khoan thép carbon trung bình, giá rẻ, chấp nhận được.",

        "diem_gia": 2,
        "diem_do_ben": 3,
        "diem_on_dinh": 3,
        "diem_chat_luong_be_mat": 3,
        "diem_san_co": 5,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Mũi khoan HSS Φ6.8",
        "ma_tool": "DRL-P-HSS-6.8",
        "nhom_tool": "Mũi khoan",
        "dong_tool": "Drill",
        "nha_san_xuat": "Totten",
        "ma_nha_sx": "HSS-6.8",
        "tieu_chuan": "DIN338",
        "model": "HSS Jobber",
        "vat_lieu_phu_hop": "C45, SS400",
        "ghi_chu": "Dùng khoan trước cho taro M8.",
        "duong_kinh": Decimal("6.80"),
        "chieu_dai_lam_viec": Decimal("60.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "1400 lỗ / tool",

        "loai_gia_cong": "DRILL",
        "duong_kinh_min": Decimal("6.70"),
        "duong_kinh_max": Decimal("6.90"),
        "ty_le_sau_lo_max": Decimal("4.0"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 15,
        "do_cung_max": 28,
        "may_phu_hop": "VMC 6000 rpm",
        "can_coolant": False,

        "ton_kho": 22,
        "muc_canh_bao": 8,
        "tu": "T1",
        "ngan": "NG1-02",
        "may_uu_tien": "Máy khoan bàn 02",
        "ngay_nhap_kho": date(2024, 12, 28),
        "gia_tri_mua": Decimal("15000"),

        "wear_max": 100,
        "nguong_thay": 80,
        "hrc_tham_chieu": 24,
        "che_do_cat_khuyen_nghi": "n=2200 rpm; f=0.14 mm/vòng",
        "ket_luan_fuzzy": "Giống tool 5.0 nhưng dùng cho đường kính lớn hơn.",

        "diem_gia": 2,
        "diem_do_ben": 3,
        "diem_on_dinh": 3,
        "diem_chat_luong_be_mat": 3,
        "diem_san_co": 4,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Mũi khoan carbide Φ8.0 phủ TiAlN",
        "ma_tool": "DRL-P-CBD-8.0-TiAlN",
        "nhom_tool": "Mũi khoan",
        "dong_tool": "Carbide Drill",
        "nha_san_xuat": "YG-1",
        "ma_nha_sx": "YG8.0-TiAlN",
        "tieu_chuan": "DIN6539",
        "model": "U Drill",
        "vat_lieu_phu_hop": "S45C, SCM440",
        "ghi_chu": "Khoan tốc độ cao, có coolant trong.",
        "duong_kinh": Decimal("8.00"),
        "chieu_dai_lam_viec": Decimal("72.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "2500 lỗ / tool",

        "loai_gia_cong": "DRILL",
        "duong_kinh_min": Decimal("7.95"),
        "duong_kinh_max": Decimal("8.02"),
        "ty_le_sau_lo_max": Decimal("8.0"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 20,
        "do_cung_max": 32,
        "may_phu_hop": "VMC 10000 rpm, có coolant trong",
        "can_coolant": True,

        "ton_kho": 8,
        "muc_canh_bao": 5,
        "tu": "T1",
        "ngan": "NG1-03",
        "may_uu_tien": "VMC-01",
        "ngay_nhap_kho": date(2025, 1, 10),
        "gia_tri_mua": Decimal("450000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 30,
        "che_do_cat_khuyen_nghi": "n=3800 rpm; f=0.18 mm/vòng; Vc≈95 m/phút",
        "ket_luan_fuzzy": "Đắt nhưng bền, phù hợp lỗ yêu cầu chính xác cao.",

        "diem_gia": 4,
        "diem_do_ben": 5,
        "diem_on_dinh": 5,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },

    # ===== NHÓM KHOAN GANG (DRILL + ISO K) – 2 tool =====
    {
        "ten_tool": "Mũi khoan gang Φ6.8",
        "ma_tool": "DRL-K-GG-6.8",
        "nhom_tool": "Mũi khoan",
        "dong_tool": "Cast Iron Drill",
        "nha_san_xuat": "Taegutec",
        "ma_nha_sx": "GG-6.8",
        "tieu_chuan": "",
        "model": "Cast Drill",
        "vat_lieu_phu_hop": "FC250, FCD450",
        "ghi_chu": "",
        "duong_kinh": Decimal("6.80"),
        "chieu_dai_lam_viec": Decimal("50.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "2000 lỗ / tool",

        "loai_gia_cong": "DRILL",
        "duong_kinh_min": Decimal("6.78"),
        "duong_kinh_max": Decimal("6.82"),
        "ty_le_sau_lo_max": Decimal("4.0"),
        "nhom_vat_lieu_iso": "K",
        "do_cung_min": 15,
        "do_cung_max": 30,
        "may_phu_hop": "VMC 8000 rpm",
        "can_coolant": True,

        "ton_kho": 12,
        "muc_canh_bao": 4,
        "tu": "T1",
        "ngan": "NG1-04",
        "may_uu_tien": "Máy khoan gang",
        "ngay_nhap_kho": date(2024, 12, 28),
        "gia_tri_mua": Decimal("230000"),

        "wear_max": 100,
        "nguong_thay": 75,
        "hrc_tham_chieu": 24,
        "che_do_cat_khuyen_nghi": "n=3200 rpm; f=0.16 mm/vòng",
        "ket_luan_fuzzy": "Tối ưu cho gang, hạn chế dùng cho thép.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 4,
        "diem_uu_tien_dung_truoc": 3,
    },
    {
        "ten_tool": "Mũi khoan gang Φ10.2",
        "ma_tool": "DRL-K-GG-10.2",
        "nhom_tool": "Mũi khoan",
        "dong_tool": "Cast Iron Drill",
        "nha_san_xuat": "Taegutec",
        "ma_nha_sx": "GG-10.2",
        "tieu_chuan": "",
        "model": "Cast Drill Long",
        "vat_lieu_phu_hop": "FC200, FC250",
        "ghi_chu": "Chiều dài làm việc lớn hơn, lỗ sâu hơn.",
        "duong_kinh": Decimal("10.20"),
        "chieu_dai_lam_viec": Decimal("80.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "1800 lỗ / tool",

        "loai_gia_cong": "DRILL",
        "duong_kinh_min": Decimal("10.18"),
        "duong_kinh_max": Decimal("10.22"),
        "ty_le_sau_lo_max": Decimal("6.0"),
        "nhom_vat_lieu_iso": "K",
        "do_cung_min": 15,
        "do_cung_max": 30,
        "may_phu_hop": "VMC 6000 rpm",
        "can_coolant": True,

        "ton_kho": 6,
        "muc_canh_bao": 2,
        "tu": "T1",
        "ngan": "NG1-05",
        "may_uu_tien": "Máy khoan lỗ sâu gang",
        "ngay_nhap_kho": date(2025, 1, 15),
        "gia_tri_mua": Decimal("280000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 24,
        "che_do_cat_khuyen_nghi": "n=2600 rpm; f=0.18 mm/vòng",
        "ket_luan_fuzzy": "Cùng nhóm với mũi 6.8 nhưng cho lỗ to hơn, sâu hơn.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },

    # ===== NHÓM PHAY THÉP (MILL + ISO P) – 3 tool =====
    {
        "ten_tool": "Dao phay ngón 4 mep Φ10 HSS",
        "ma_tool": "EM-P-HSS-4F-10",
        "nhom_tool": "Dao phay",
        "dong_tool": "Endmill",
        "nha_san_xuat": "OSG",
        "ma_nha_sx": "HSS-4F-10",
        "tieu_chuan": "JIS",
        "model": "Standard Endmill",
        "vat_lieu_phu_hop": "S45C, SS400",
        "ghi_chu": "",
        "duong_kinh": Decimal("10.00"),
        "chieu_dai_lam_viec": Decimal("25.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "8 giờ gia công / tool",

        "loai_gia_cong": "MILL",
        "duong_kinh_min": Decimal("9.95"),
        "duong_kinh_max": Decimal("10.02"),
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 15,
        "do_cung_max": 30,
        "may_phu_hop": "VMC 6000 rpm",
        "can_coolant": True,

        "ton_kho": 15,
        "muc_canh_bao": 5,
        "tu": "T2",
        "ngan": "NG2-01",
        "may_uu_tien": "VMC-02",
        "ngay_nhap_kho": date(2024, 12, 20),
        "gia_tri_mua": Decimal("180000"),

        "wear_max": 100,
        "nguong_thay": 75,
        "hrc_tham_chieu": 25,
        "che_do_cat_khuyen_nghi": "n=2200 rpm; fz=0.05 mm/răng; ap=1.0 mm; ae=5.0 mm",
        "ket_luan_fuzzy": "Dao phay đa dụng, dùng phay thô – bán tinh.",

        "diem_gia": 3,
        "diem_do_ben": 3,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 4,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Dao phay ngón 4 mep Φ12 HSS phủ",
        "ma_tool": "EM-P-HSS-4F-12-COTING",
        "nhom_tool": "Dao phay",
        "dong_tool": "Endmill",
        "nha_san_xuat": "OSG",
        "ma_nha_sx": "HSS-4F-12-C",
        "tieu_chuan": "JIS",
        "model": "Coated Endmill",
        "vat_lieu_phu_hop": "S45C, SCM440",
        "ghi_chu": "Có phủ tăng tuổi thọ.",
        "duong_kinh": Decimal("12.00"),
        "chieu_dai_lam_viec": Decimal("30.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "10 giờ gia công / tool",

        "loai_gia_cong": "MILL",
        "duong_kinh_min": Decimal("11.96"),
        "duong_kinh_max": Decimal("12.02"),
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 18,
        "do_cung_max": 32,
        "may_phu_hop": "VMC 8000 rpm",
        "can_coolant": True,

        "ton_kho": 10,
        "muc_canh_bao": 4,
        "tu": "T2",
        "ngan": "NG2-02",
        "may_uu_tien": "VMC-02",
        "ngay_nhap_kho": date(2025, 1, 3),
        "gia_tri_mua": Decimal("260000"),

        "wear_max": 100,
        "nguong_thay": 75,
        "hrc_tham_chieu": 28,
        "che_do_cat_khuyen_nghi": "n=2600 rpm; fz=0.06 mm/răng; ap=1.5 mm; ae=6.0 mm",
        "ket_luan_fuzzy": "Cùng nhóm với Φ10 nhưng bền hơn, phù hợp thô và bán tinh.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 4,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Dao phay carbide thép Φ8",
        "ma_tool": "EM-P-CBD-4F-8",
        "nhom_tool": "Dao phay",
        "dong_tool": "Carbide Endmill",
        "nha_san_xuat": "YG-1",
        "ma_nha_sx": "CBD-4F-8",
        "tieu_chuan": "",
        "model": "General Carbide",
        "vat_lieu_phu_hop": "S45C, SCM440",
        "ghi_chu": "Carbide, tuổi thọ cao hơn HSS.",
        "duong_kinh": Decimal("8.00"),
        "chieu_dai_lam_viec": Decimal("20.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "14 giờ gia công / tool",

        "loai_gia_cong": "MILL",
        "duong_kinh_min": Decimal("7.98"),
        "duong_kinh_max": Decimal("8.02"),
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 20,
        "do_cung_max": 32,
        "may_phu_hop": "VMC 10000 rpm",
        "can_coolant": True,

        "ton_kho": 6,
        "muc_canh_bao": 3,
        "tu": "T2",
        "ngan": "NG2-03",
        "may_uu_tien": "VMC-01, VMC-02",
        "ngay_nhap_kho": date(2025, 1, 12),
        "gia_tri_mua": Decimal("420000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 30,
        "che_do_cat_khuyen_nghi": "n=3800 rpm; fz=0.05 mm/răng; ap=1.0 mm; ae=4.0 mm",
        "ket_luan_fuzzy": "Hiệu suất cao, phù hợp chạy lâu, chi tiết nhiều số lượng.",

        "diem_gia": 4,
        "diem_do_ben": 5,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },

    # ===== NHÓM PHAY NHÔM (MILL + ISO N) – 2 tool =====
    {
        "ten_tool": "Dao phay carbide Φ12 chuyên nhôm",
        "ma_tool": "EM-N-CBD-AL-12",
        "nhom_tool": "Dao phay",
        "dong_tool": "Alu Endmill",
        "nha_san_xuat": "Mitsubishi",
        "ma_nha_sx": "AL-3F-12",
        "tieu_chuan": "",
        "model": "Aluminum 3F",
        "vat_lieu_phu_hop": "A6061, A5052",
        "ghi_chu": "Lưỡi cắt sắc, dùng không coolant hơi kém.",
        "duong_kinh": Decimal("12.00"),
        "chieu_dai_lam_viec": Decimal("30.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "12 giờ gia công / tool",

        "loai_gia_cong": "MILL",
        "duong_kinh_min": Decimal("11.98"),
        "duong_kinh_max": Decimal("12.01"),
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "N",
        "do_cung_min": 5,
        "do_cung_max": 20,
        "may_phu_hop": "VMC 12000 rpm",
        "can_coolant": False,

        "ton_kho": 6,
        "muc_canh_bao": 3,
        "tu": "T2",
        "ngan": "NG2-05",
        "may_uu_tien": "VMC-03 gia công nhôm",
        "ngay_nhap_kho": date(2025, 1, 18),
        "gia_tri_mua": Decimal("520000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 12,
        "che_do_cat_khuyen_nghi": "n=9000 rpm; fz=0.07 mm/răng; ap=1.0 mm; ae=6.0 mm",
        "ket_luan_fuzzy": "Rất phù hợp phay nhôm tốc độ cao, bề mặt đẹp.",

        "diem_gia": 4,
        "diem_do_ben": 4,
        "diem_on_dinh": 5,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },
    {
        "ten_tool": "Dao phay carbide Φ6 chuyên nhôm",
        "ma_tool": "EM-N-CBD-AL-6",
        "nhom_tool": "Dao phay",
        "dong_tool": "Alu Endmill",
        "nha_san_xuat": "Mitsubishi",
        "ma_nha_sx": "AL-3F-6",
        "tieu_chuan": "",
        "model": "Aluminum 3F",
        "vat_lieu_phu_hop": "A6061, A5052",
        "ghi_chu": "",
        "duong_kinh": Decimal("6.00"),
        "chieu_dai_lam_viec": Decimal("18.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "10 giờ gia công / tool",

        "loai_gia_cong": "MILL",
        "duong_kinh_min": Decimal("5.98"),
        "duong_kinh_max": Decimal("6.01"),
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "N",
        "do_cung_min": 5,
        "do_cung_max": 20,
        "may_phu_hop": "VMC 15000 rpm",
        "can_coolant": False,

        "ton_kho": 9,
        "muc_canh_bao": 3,
        "tu": "T2",
        "ngan": "NG2-06",
        "may_uu_tien": "VMC-03 gia công nhôm",
        "ngay_nhap_kho": date(2025, 1, 19),
        "gia_tri_mua": Decimal("420000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 12,
        "che_do_cat_khuyen_nghi": "n=11000 rpm; fz=0.06 mm/răng; ap=0.8 mm; ae=3.0 mm",
        "ket_luan_fuzzy": "Cùng nhóm với Φ12 nhưng linh hoạt chi tiết nhỏ.",

        "diem_gia": 4,
        "diem_do_ben": 4,
        "diem_on_dinh": 5,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },

    # ===== NHÓM TARO THÉP (TAP + ISO P) – 2 tool =====
    {
        "ten_tool": "Mũi taro M10 HSS",
        "ma_tool": "TAP-P-HSS-M10",
        "nhom_tool": "Mũi taro",
        "dong_tool": "Spiral Tap",
        "nha_san_xuat": "Yamawa",
        "ma_nha_sx": "SP-M10",
        "tieu_chuan": "ISO",
        "model": "Spiral Flute",
        "vat_lieu_phu_hop": "S45C, SS400",
        "ghi_chu": "Dùng cho lỗ thông và lỗ kín.",
        "duong_kinh": Decimal("10.00"),
        "chieu_dai_lam_viec": None,
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "1000 lỗ / tool",

        "loai_gia_cong": "TAP",
        "duong_kinh_min": Decimal("9.95"),
        "duong_kinh_max": Decimal("10.05"),
        "ty_le_sau_lo_max": Decimal("2.5"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 15,
        "do_cung_max": 28,
        "may_phu_hop": "VMC 4000 rpm, mode taro",
        "can_coolant": True,

        "ton_kho": 20,
        "muc_canh_bao": 8,
        "tu": "T3",
        "ngan": "NG3-01",
        "may_uu_tien": "VMC-01, VMC-02",
        "ngay_nhap_kho": date(2024, 11, 30),
        "gia_tri_mua": Decimal("85000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 22,
        "che_do_cat_khuyen_nghi": "n=800 rpm; f=1.5 mm/vòng (bước M10)",
        "ket_luan_fuzzy": "Taro ổn định, ít gãy nếu bôi trơn tốt.",

        "diem_gia": 3,
        "diem_do_ben": 3,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 5,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Mũi taro M8 HSS phủ",
        "ma_tool": "TAP-P-HSS-M8-COTING",
        "nhom_tool": "Mũi taro",
        "dong_tool": "Spiral Tap",
        "nha_san_xuat": "Yamawa",
        "ma_nha_sx": "SP-M8-C",
        "tieu_chuan": "ISO",
        "model": "Coated Spiral",
        "vat_lieu_phu_hop": "S45C, SCM435",
        "ghi_chu": "",
        "duong_kinh": Decimal("8.00"),
        "chieu_dai_lam_viec": None,
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "1200 lỗ / tool",

        "loai_gia_cong": "TAP",
        "duong_kinh_min": Decimal("7.95"),
        "duong_kinh_max": Decimal("8.05"),
        "ty_le_sau_lo_max": Decimal("2.0"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 18,
        "do_cung_max": 30,
        "may_phu_hop": "VMC 4000 rpm",
        "can_coolant": True,

        "ton_kho": 16,
        "muc_canh_bao": 6,
        "tu": "T3",
        "ngan": "NG3-02",
        "may_uu_tien": "VMC-02",
        "ngay_nhap_kho": date(2024, 12, 15),
        "gia_tri_mua": Decimal("90000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 24,
        "che_do_cat_khuyen_nghi": "n=900 rpm; f=1.25 mm/vòng (bước M8)",
        "ket_luan_fuzzy": "So với M10, tool này bền hơn, ren đẹp hơn.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 5,
        "diem_uu_tien_dung_truoc": 4,
    },

    # ===== NHÓM DOA (REAM + ISO P) – 2 tool =====
    {
        "ten_tool": "Mũi doa Φ12 H7",
        "ma_tool": "REAM-P-HSS-12-H7",
        "nhom_tool": "Mũi doa",
        "dong_tool": "Reamer",
        "nha_san_xuat": "NT Tool",
        "ma_nha_sx": "RM-12-H7",
        "tieu_chuan": "H7",
        "model": "Machine Reamer",
        "vat_lieu_phu_hop": "S45C",
        "ghi_chu": "Dùng để doa tinh lỗ khoan 11.8mm.",
        "duong_kinh": Decimal("12.00"),
        "chieu_dai_lam_viec": Decimal("30.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "500 lỗ / tool",

        "loai_gia_cong": "REAM",
        "duong_kinh_min": Decimal("11.99"),
        "duong_kinh_max": Decimal("12.01"),
        "ty_le_sau_lo_max": Decimal("3.0"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 15,
        "do_cung_max": 28,
        "may_phu_hop": "VMC 3000 rpm",
        "can_coolant": True,

        "ton_kho": 5,
        "muc_canh_bao": 2,
        "tu": "T3",
        "ngan": "NG3-03",
        "may_uu_tien": "Máy doa lỗ chính xác",
        "ngay_nhap_kho": date(2025, 1, 2),
        "gia_tri_mua": Decimal("260000"),

        "wear_max": 100,
        "nguong_thay": 60,
        "hrc_tham_chieu": 20,
        "che_do_cat_khuyen_nghi": "n=600 rpm; f=0.1 mm/vòng; có coolant",
        "ket_luan_fuzzy": "Dùng khi cần độ chính xác lỗ cao, bề mặt đẹp.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 5,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },
    {
        "ten_tool": "Mũi doa Φ10 H7",
        "ma_tool": "REAM-P-HSS-10-H7",
        "nhom_tool": "Mũi doa",
        "dong_tool": "Reamer",
        "nha_san_xuat": "NT Tool",
        "ma_nha_sx": "RM-10-H7",
        "tieu_chuan": "H7",
        "model": "Machine Reamer",
        "vat_lieu_phu_hop": "S45C, S50C",
        "ghi_chu": "",
        "duong_kinh": Decimal("10.00"),
        "chieu_dai_lam_viec": Decimal("25.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "450 lỗ / tool",

        "loai_gia_cong": "REAM",
        "duong_kinh_min": Decimal("9.99"),
        "duong_kinh_max": Decimal("10.01"),
        "ty_le_sau_lo_max": Decimal("3.0"),
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 15,
        "do_cung_max": 28,
        "may_phu_hop": "VMC 3000 rpm",
        "can_coolant": True,

        "ton_kho": 7,
        "muc_canh_bao": 3,
        "tu": "T3",
        "ngan": "NG3-04",
        "may_uu_tien": "Máy doa lỗ chính xác",
        "ngay_nhap_kho": date(2025, 1, 5),
        "gia_tri_mua": Decimal("240000"),

        "wear_max": 100,
        "nguong_thay": 60,
        "hrc_tham_chieu": 20,
        "che_do_cat_khuyen_nghi": "n=650 rpm; f=0.09 mm/vòng; có coolant",
        "ket_luan_fuzzy": "Cùng nhóm với Φ12 nhưng cho lỗ nhỏ hơn, yêu cầu tương tự.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 5,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },

    # ===== NHÓM TIỆN THÉP & INOX (TURN + ISO P/M) – 3 tool =====
    {
        "ten_tool": "Insert tiện thép CNMG120408",
        "ma_tool": "TURN-P-INS-CNMG120408",
        "nhom_tool": "Insert tiện",
        "dong_tool": "CNMG",
        "nha_san_xuat": "Sandvik",
        "ma_nha_sx": "CNMG120408-PM",
        "tieu_chuan": "ISO",
        "model": "PM Grade",
        "vat_lieu_phu_hop": "S45C, SCM440",
        "ghi_chu": "Dùng tiện thô và bán tinh.",
        "duong_kinh": None,
        "chieu_dai_lam_viec": None,
        "don_vi_tinh": "miếng",
        "tuoi_tho_chuan": "30 phút cắt / cạnh",

        "loai_gia_cong": "TURN",
        "duong_kinh_min": None,
        "duong_kinh_max": None,
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 20,
        "do_cung_max": 32,
        "may_phu_hop": "Máy tiện CNC 2000 rpm",
        "can_coolant": True,

        "ton_kho": 40,
        "muc_canh_bao": 15,
        "tu": "T4",
        "ngan": "NG4-01",
        "may_uu_tien": "Máy tiện CNC-01",
        "ngay_nhap_kho": date(2024, 12, 10),
        "gia_tri_mua": Decimal("35000"),

        "wear_max": 100,
        "nguong_thay": 80,
        "hrc_tham_chieu": 28,
        "che_do_cat_khuyen_nghi": "Vc=180 m/phút; f=0.25 mm/vòng; ap=1.5 mm",
        "ket_luan_fuzzy": "Insert tiện thép đa dụng, ưu tiên dùng cho chi tiết thường.",

        "diem_gia": 2,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 4,
        "diem_san_co": 5,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Insert tiện thép CNMG120404 tinh",
        "ma_tool": "TURN-P-INS-CNMG120404",
        "nhom_tool": "Insert tiện",
        "dong_tool": "CNMG",
        "nha_san_xuat": "Sandvik",
        "ma_nha_sx": "CNMG120404-FM",
        "tieu_chuan": "ISO",
        "model": "FM Grade",
        "vat_lieu_phu_hop": "S45C, SCM440",
        "ghi_chu": "Chuyên tinh, bề mặt đẹp.",
        "duong_kinh": None,
        "chieu_dai_lam_viec": None,
        "don_vi_tinh": "miếng",
        "tuoi_tho_chuan": "25 phút cắt / cạnh",

        "loai_gia_cong": "TURN",
        "duong_kinh_min": None,
        "duong_kinh_max": None,
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "P",
        "do_cung_min": 20,
        "do_cung_max": 32,
        "may_phu_hop": "Máy tiện CNC 2500 rpm",
        "can_coolant": True,

        "ton_kho": 24,
        "muc_canh_bao": 10,
        "tu": "T4",
        "ngan": "NG4-02",
        "may_uu_tien": "Máy tiện CNC-01, CNC-02",
        "ngay_nhap_kho": date(2025, 1, 4),
        "gia_tri_mua": Decimal("38000"),

        "wear_max": 100,
        "nguong_thay": 80,
        "hrc_tham_chieu": 28,
        "che_do_cat_khuyen_nghi": "Vc=220 m/phút; f=0.15 mm/vòng; ap=0.8 mm",
        "ket_luan_fuzzy": "Cùng nhóm CNMG nhưng thiên về tinh, bề mặt đẹp hơn.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 4,
        "diem_uu_tien_dung_truoc": 4,
    },
    {
        "ten_tool": "Insert tiện inox VNMG160404",
        "ma_tool": "TURN-M-INS-VNMG160404",
        "nhom_tool": "Insert tiện",
        "dong_tool": "VNMG",
        "nha_san_xuat": "Kyocera",
        "ma_nha_sx": "VNMG160404-MF",
        "tieu_chuan": "ISO",
        "model": "MF Grade",
        "vat_lieu_phu_hop": "SUS304, SUS316",
        "ghi_chu": "",
        "duong_kinh": None,
        "chieu_dai_lam_viec": None,
        "don_vi_tinh": "miếng",
        "tuoi_tho_chuan": "20 phút cắt / cạnh",

        "loai_gia_cong": "TURN",
        "duong_kinh_min": None,
        "duong_kinh_max": None,
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "M",
        "do_cung_min": 15,
        "do_cung_max": 28,
        "may_phu_hop": "Máy tiện CNC 2500 rpm",
        "can_coolant": True,

        "ton_kho": 18,
        "muc_canh_bao": 6,
        "tu": "T4",
        "ngan": "NG4-03",
        "may_uu_tien": "Máy tiện CNC-02",
        "ngay_nhap_kho": date(2025, 1, 8),
        "gia_tri_mua": Decimal("42000"),

        "wear_max": 100,
        "nguong_thay": 70,
        "hrc_tham_chieu": 22,
        "che_do_cat_khuyen_nghi": "Vc=140 m/phút; f=0.18 mm/vòng; ap=1.0 mm",
        "ket_luan_fuzzy": "Dùng riêng cho inox để tăng tuổi thọ và bề mặt.",

        "diem_gia": 3,
        "diem_do_ben": 4,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 3,
        "diem_uu_tien_dung_truoc": 3,
    },

    # ===== NHÓM PHAY THÉP ĐÃ TÔI (MILL + ISO H) – 1 tool chuyên dụng =====
    {
        "ten_tool": "Dao phay carbide thép tôi Φ8",
        "ma_tool": "EM-H-CBD-HARD-8",
        "nhom_tool": "Dao phay",
        "dong_tool": "Hardmill",
        "nha_san_xuat": "Hitachi",
        "ma_nha_sx": "HM-8",
        "tieu_chuan": "",
        "model": "Hard Milling",
        "vat_lieu_phu_hop": "SKD11 55–60HRC",
        "ghi_chu": "Chỉ dùng cho thép đã tôi.",
        "duong_kinh": Decimal("8.00"),
        "chieu_dai_lam_viec": Decimal("20.00"),
        "don_vi_tinh": "cái",
        "tuoi_tho_chuan": "8 giờ gia công / tool",

        "loai_gia_cong": "MILL",
        "duong_kinh_min": Decimal("7.98"),
        "duong_kinh_max": Decimal("8.01"),
        "ty_le_sau_lo_max": None,
        "nhom_vat_lieu_iso": "H",
        "do_cung_min": 50,
        "do_cung_max": 62,
        "may_phu_hop": "VMC 15000 rpm, độ cứng vững cao",
        "can_coolant": False,

        "ton_kho": 4,
        "muc_canh_bao": 2,
        "tu": "T2",
        "ngan": "NG2-07",
        "may_uu_tien": "Máy phay khuôn",
        "ngay_nhap_kho": date(2025, 1, 20),
        "gia_tri_mua": Decimal("980000"),

        "wear_max": 100,
        "nguong_thay": 65,
        "hrc_tham_chieu": 58,
        "che_do_cat_khuyen_nghi": "n=12000 rpm; fz=0.02 mm/răng; ap=0.2 mm; ae=0.3 mm",
        "ket_luan_fuzzy": "Tool chuyên dụng, không dùng lung tung để tránh mẻ.",

        "diem_gia": 5,
        "diem_do_ben": 5,
        "diem_on_dinh": 4,
        "diem_chat_luong_be_mat": 5,
        "diem_san_co": 2,
        "diem_uu_tien_dung_truoc": 2,
    },
]

created_count = 0
updated_count = 0

for data in tools_data:
    ma_tool = data["ma_tool"]
    obj, created = Tool.objects.update_or_create(
        ma_tool=ma_tool,
        defaults=data,
    )
    if created:
        created_count += 1
        print(f"Tạo mới tool: {obj}")
    else:
        updated_count += 1
        print(f"Cập nhật tool: {obj}")

print(f"\nHoàn thành. Đã tạo mới {created_count} tool, cập nhật {updated_count} tool.")
