# Generated by Django 5.2.5 on 2025-11-22 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holder', '0002_holder_ma_nhom_tuong_thich_holder_tool_khuyen_dung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thiet_bi_snapshot', models.CharField(blank=True, help_text='Copy từ Holder.ten_thiet_bi tại thời điểm mượn', max_length=200, verbose_name='Tên thiết bị (snapshot)')),
                ('ma_noi_bo_snapshot', models.CharField(blank=True, help_text='Copy từ Holder.ma_noi_bo tại thời điểm mượn', max_length=50, verbose_name='Mã nội bộ (snapshot)')),
                ('muc_dich', models.CharField(choices=[('SU_DUNG', 'Mượn để sử dụng'), ('BAO_TRI', 'Đem đi bảo trì')], max_length=20, verbose_name='Mục đích mượn')),
                ('du_an', models.CharField(blank=True, max_length=100, verbose_name='Dự án / lệnh sản xuất')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả chi tiết / ghi chú')),
                ('thoi_gian_muon', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian mượn')),
                ('thoi_gian_tra', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian trả')),
                ('thoi_luong_phut', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời lượng sử dụng (phút)')),
                ('mon_truoc', models.PositiveIntegerField(blank=True, help_text='Từ Holder.mon tại thời điểm mượn', null=True, verbose_name='% mòn trước khi mượn')),
                ('mon_sau', models.PositiveIntegerField(blank=True, help_text='Sau khi trừ hao / reset bảo trì', null=True, verbose_name='% mòn sau khi trả')),
                ('trang_thai', models.CharField(choices=[('DANG_MUON', 'Đang mượn'), ('DA_TRA', 'Đã trả')], default='DANG_MUON', max_length=20, verbose_name='Trạng thái mượn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='holder.holder', verbose_name='Holder')),
                ('nguoi_thuc_hien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử mượn holder',
                'verbose_name_plural': 'Lịch sử mượn holder',
                'ordering': ['-thoi_gian_muon'],
            },
        ),
    ]
