# Generated by Django 5.2.5 on 2025-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder_muontra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holderhistory',
            name='mon_sau',
            field=models.PositiveIntegerField(blank=True, help_text='Sau khi trừ hao / reset bảo trì (0–100)', null=True, verbose_name='% độ bền sau khi trả'),
        ),
        migrations.AlterField(
            model_name='holderhistory',
            name='mon_truoc',
            field=models.PositiveIntegerField(blank=True, help_text='Từ Holder.mon tại thời điểm mượn (0–100)', null=True, verbose_name='% độ bền trước khi mượn'),
        ),
    ]
