# Generated by Django 5.2.5 on 2025-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder_muontra', '0002_alter_holderhistory_mon_sau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holderhistory',
            name='ly_do_fail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='holderhistory',
            name='tx_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='holderhistory',
            name='trang_thai',
            field=models.CharField(choices=[('PENDING', 'Đang chờ tủ xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('DANG_MUON', 'Đang mượn'), ('DA_TRA', 'Đã trả')], default='PENDING', max_length=20),
        ),
    ]
