# Generated by Django 5.2.5 on 2025-11-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Trợ lý TMS', max_length=100, verbose_name='Tên chatbot hiển thị')),
                ('enable_smalltalk', models.BooleanField(default=True, verbose_name='Cho phép smalltalk / chào hỏi')),
                ('max_search_results', models.PositiveIntegerField(default=3, verbose_name='Số gợi ý search tối đa')),
                ('max_fuzzy_suggestions', models.PositiveIntegerField(default=3, verbose_name='Số gợi ý fuzzy tối đa')),
                ('search_auto_show_threshold', models.FloatField(default=0.9, verbose_name='Ngưỡng search auto show (0–1)')),
                ('fuzzy_need_more_info_threshold', models.FloatField(default=0.4, verbose_name='Ngưỡng fuzzy cần hỏi thêm (0–1)')),
                ('enable_debug_block', models.BooleanField(default=False, verbose_name='Bật DEBUG trong câu trả lời')),
                ('tone', models.CharField(choices=[('formal', 'Trang trọng'), ('casual', 'Thân mật')], default='casual', max_length=20, verbose_name='Giọng điệu trả lời')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Chatbot',
                'verbose_name_plural': 'Cấu hình Chatbot',
            },
        ),
    ]
