# Generated by Django 5.2.5 on 2025-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzyRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_text', models.TextField()),
                ('criteria_json', models.JSONField()),
                ('results_json', models.JSONField()),
            ],
        ),
    ]
