# Generated by Django 5.2.5 on 2025-11-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='can_coolant',
            field=models.BooleanField(default=False, verbose_name='Yêu cầu tưới nguội'),
        ),
        migrations.AddField(
            model_name='tool',
            name='diem_chat_luong_be_mat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Chất lượng bề mặt (1=thô, 5=rất đẹp)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='diem_do_ben',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm độ bền (1=thấp, 5=rất bền)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='diem_gia',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm giá (1=rẻ, 5=rất đắt)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='diem_on_dinh',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Độ ổn định quá trình (1=kém, 5=rất ổn định)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='diem_san_co',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Độ sẵn có (1=khó mua, 5=luôn sẵn)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='diem_uu_tien_dung_truoc',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mức ưu tiên dùng trước (1=ít, 5=ưu tiên cao)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='do_cung_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Độ cứng vật liệu max (HRC)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='do_cung_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Độ cứng vật liệu min (HRC)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='duong_kinh_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ĐK max cho phép (mm)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='duong_kinh_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ĐK min cho phép (mm)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='loai_gia_cong',
            field=models.CharField(blank=True, choices=[('DRILL', 'Khoan'), ('MILL', 'Phay'), ('TAP', 'Taro'), ('REAM', 'Doa'), ('TURN', 'Tiện')], help_text='Khoan / Phay / Taro / Doa / Tiện…', max_length=50, null=True, verbose_name='Loại gia công chính'),
        ),
        migrations.AddField(
            model_name='tool',
            name='may_phu_hop',
            field=models.CharField(blank=True, help_text='VD: VMC 10.000 rpm, CNC tiện, Máy khoan bàn…', max_length=200, verbose_name='Dòng máy phù hợp'),
        ),
        migrations.AddField(
            model_name='tool',
            name='nhom_vat_lieu_iso',
            field=models.CharField(blank=True, choices=[('P', 'Thép (ISO P)'), ('M', 'Thép không gỉ (ISO M)'), ('K', 'Gang (ISO K)'), ('N', 'Nhôm/kim loại màu (ISO N)'), ('S', 'Hợp kim chịu nhiệt (ISO S)'), ('H', 'Thép đã tôi (ISO H)')], max_length=2, verbose_name='Nhóm vật liệu ISO'),
        ),
        migrations.AddField(
            model_name='tool',
            name='ty_le_sau_lo_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Tỷ lệ sâu lỗ max (L/D)'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['ma_tool'], name='tool_tool_ma_tool_c332a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['nhom_tool', 'dong_tool'], name='tool_tool_nhom_to_468c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['loai_gia_cong', 'nhom_vat_lieu_iso'], name='tool_tool_loai_gi_22d2d4_idx'),
        ),
    ]
