# Generated by Django 5.2.5 on 2025-11-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tool', models.CharField(max_length=200, verbose_name='Tên tool')),
                ('ma_tool', models.CharField(max_length=50, unique=True, verbose_name='Mã tool')),
                ('nhom_tool', models.CharField(help_text='VD: Mũi khoan, Dao phay, Mũi taro…', max_length=100, verbose_name='Nhóm tool')),
                ('dong_tool', models.CharField(blank=True, help_text='VD: Drill, Endmill, Tap…', max_length=100, verbose_name='Dòng tool')),
                ('nha_san_xuat', models.CharField(blank=True, max_length=100, verbose_name='Nhà sản xuất')),
                ('ma_nha_sx', models.CharField(blank=True, max_length=100, verbose_name='Mã nhà sản xuất')),
                ('tieu_chuan', models.CharField(blank=True, max_length=100, verbose_name='Tiêu chuẩn')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('vat_lieu_phu_hop', models.CharField(blank=True, help_text='VD: C45, S50C, SUS304…', max_length=200, verbose_name='Vật liệu gia công phù hợp')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
                ('duong_kinh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Đường kính làm việc (mm)')),
                ('chieu_dai_lam_viec', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Chiều dài làm việc (mm)')),
                ('don_vi_tinh', models.CharField(blank=True, help_text='VD: cái, hộp, bộ…', max_length=50, verbose_name='Đơn vị tính')),
                ('tuoi_tho_chuan', models.CharField(blank=True, help_text='VD: 1500 lỗ / 1 tool', max_length=100, verbose_name='Tuổi thọ chuẩn')),
                ('ton_kho', models.PositiveIntegerField(default=0, verbose_name='Tồn kho hiện tại')),
                ('muc_canh_bao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mức cảnh báo tối thiểu')),
                ('tu', models.CharField(blank=True, max_length=100, verbose_name='Tủ / Kệ')),
                ('ngan', models.CharField(blank=True, max_length=100, verbose_name='Ngăn / Khay')),
                ('may_uu_tien', models.CharField(blank=True, max_length=100, verbose_name='Máy / Line ưu tiên')),
                ('ngay_nhap_kho', models.DateField(blank=True, null=True, verbose_name='Ngày nhập kho')),
                ('gia_tri_mua', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Giá trị mua (VND/đv)')),
                ('wear_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Độ mòn tối đa (%)')),
                ('nguong_thay', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ngưỡng cảnh báo thay (%)')),
                ('hrc_tham_chieu', models.PositiveIntegerField(blank=True, null=True, verbose_name='Độ cứng vật liệu tham chiếu (HRC)')),
                ('che_do_cat_khuyen_nghi', models.TextField(blank=True, verbose_name='Chế độ cắt khuyến nghị')),
                ('ket_luan_fuzzy', models.TextField(blank=True, verbose_name='Kết luận fuzzy / khuyến nghị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name': 'Tool tiêu hao',
                'verbose_name_plural': 'Tool tiêu hao',
                'ordering': ['ten_tool', 'ma_tool'],
            },
        ),
    ]
