# Generated by Django 5.2.5 on 2025-12-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_tool_can_coolant_tool_diem_chat_luong_be_mat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='ngan',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ngăn (số)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tu',
            field=models.CharField(blank=True, max_length=1, verbose_name='Tủ (A/B/...)'),
        ),
    ]
