from holder.models import Holder
from datetime import date

# 9 loại holder cơ bản
base_types = [
    {
        "ten_thiet_bi": "Holder HSK63A ER32 L=100",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-HSK63A-ER32-100",
        "ma_nha_sx": "HSK63A-ER32-100",
        "loai_holder": "HSK63A ER32",
        "so_serial_prefix": "SN-HSK63A-ER32-100",
        "nha_san_xuat": "SUMITOMO",
        "nha_cung_cap": "Công ty TNHH ABC",
        "nguoi_quan_ly": "Nguyễn Văn A",
        "chuan_ga": "HSK63A",
        "loai_kep": "ER32",
        "chieu_dai_lam_viec": 100,
        "duong_kinh_kep_max": 20,
        "gia_tri_mua": 5200000,
        "chu_ky_kiem_tra": "6 tháng / lần",
        "cv": 8.5,
        "dx": 9.0,
        "mon": 10,
        "tan_suat": 12,
        "ld": 100,
        "ket_luan_fuzzy": "Holder cứng vững, ưu tiên dùng cho dao phay ngón Ø6–Ø20.",
    },
    {
        "ten_thiet_bi": "Holder HSK63A ER40 L=120",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-HSK63A-ER40-120",
        "ma_nha_sx": "HSK63A-ER40-120",
        "loai_holder": "HSK63A ER40",
        "so_serial_prefix": "SN-HSK63A-ER40-120",
        "nha_san_xuat": "SUMITOMO",
        "nha_cung_cap": "Công ty TNHH ABC",
        "nguoi_quan_ly": "Nguyễn Văn A",
        "chuan_ga": "HSK63A",
        "loai_kep": "ER40",
        "chieu_dai_lam_viec": 120,
        "duong_kinh_kep_max": 26,
        "gia_tri_mua": 5800000,
        "chu_ky_kiem_tra": "6 tháng / lần",
        "cv": 8.0,
        "dx": 8.8,
        "mon": 12,
        "tan_suat": 10,
        "ld": 120,
        "ket_luan_fuzzy": "Phù hợp dao phay thô đường kính lớn, chế độ cắt nặng.",
    },
    {
        "ten_thiet_bi": "Holder BT40 ER32 L=100",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-BT40-ER32-100",
        "ma_nha_sx": "BT40-ER32-100",
        "loai_holder": "BT40 ER32",
        "so_serial_prefix": "SN-BT40-ER32-100",
        "nha_san_xuat": "YG-1",
        "nha_cung_cap": "Công ty TNHH XYZ",
        "nguoi_quan_ly": "Trần Văn B",
        "chuan_ga": "BT40",
        "loai_kep": "ER32",
        "chieu_dai_lam_viec": 100,
        "duong_kinh_kep_max": 20,
        "gia_tri_mua": 3200000,
        "chu_ky_kiem_tra": "1 năm / lần",
        "cv": 7.5,
        "dx": 8.5,
        "mon": 8,
        "tan_suat": 15,
        "ld": 90,
        "ket_luan_fuzzy": "Holder tiêu chuẩn cho máy BT40, dùng đa năng.",
    },
    {
        "ten_thiet_bi": "Holder BT40 collet Ø6–20",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-BT40-COLLET-06-20",
        "ma_nha_sx": "BT40-COLLET-06-20",
        "loai_holder": "BT40 Collet",
        "so_serial_prefix": "SN-BT40-COLLET-06-20",
        "nha_san_xuat": "OSG",
        "nha_cung_cap": "Công ty TNHH XYZ",
        "nguoi_quan_ly": "Trần Văn B",
        "chuan_ga": "BT40",
        "loai_kep": "Collet",
        "chieu_dai_lam_viec": 110,
        "duong_kinh_kep_max": 20,
        "gia_tri_mua": 3000000,
        "chu_ky_kiem_tra": "1 năm / lần",
        "cv": 7.8,
        "dx": 8.2,
        "mon": 5,
        "tan_suat": 18,
        "ld": 95,
        "ket_luan_fuzzy": "Dùng cho các loại dao phay nhỏ và trung bình.",
    },
    {
        "ten_thiet_bi": "Holder HSK63A dao phay mặt D80",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-HSK63A-FACE-80",
        "ma_nha_sx": "HSK63A-FACE-80",
        "loai_holder": "HSK63A Face Mill",
        "so_serial_prefix": "SN-HSK63A-FACE-80",
        "nha_san_xuat": "TaeguTec",
        "nha_cung_cap": "Công ty TNHH ABC",
        "nguoi_quan_ly": "Nguyễn Văn A",
        "chuan_ga": "HSK63A",
        "loai_kep": "Mặt đầu",
        "chieu_dai_lam_viec": 60,
        "duong_kinh_kep_max": 80,
        "gia_tri_mua": 7500000,
        "chu_ky_kiem_tra": "6 tháng / lần",
        "cv": 9.0,
        "dx": 8.5,
        "mon": 6,
        "tan_suat": 8,
        "ld": 70,
        "ket_luan_fuzzy": "Phù hợp phay mặt tinh, yêu cầu độ phẳng cao.",
    },
    {
        "ten_thiet_bi": "Holder HSK63A shrink-fit Ø10",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-HSK63A-SHRINK-10",
        "ma_nha_sx": "HSK63A-SHRINK-10",
        "loai_holder": "HSK63A Shrink-fit",
        "so_serial_prefix": "SN-HSK63A-SHRINK-10",
        "nha_san_xuat": "Haimer",
        "nha_cung_cap": "Công ty TNHH DEF",
        "nguoi_quan_ly": "Lê Văn C",
        "chuan_ga": "HSK63A",
        "loai_kep": "Shrink-fit",
        "chieu_dai_lam_viec": 120,
        "duong_kinh_kep_max": 10,
        "gia_tri_mua": 9800000,
        "chu_ky_kiem_tra": "6 tháng / lần",
        "cv": 9.5,
        "dx": 9.5,
        "mon": 3,
        "tan_suat": 5,
        "ld": 120,
        "ket_luan_fuzzy": "Dùng cho gia công tốc độ cao, độ đảo rất nhỏ.",
    },
    {
        "ten_thiet_bi": "Holder BT50 đầu khoan 1–13mm",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-BT50-DRILL-1-13",
        "ma_nha_sx": "BT50-DRILL-1-13",
        "loai_holder": "BT50 Drill Chuck",
        "so_serial_prefix": "SN-BT50-DRILL-1-13",
        "nha_san_xuat": "Nikken",
        "nha_cung_cap": "Công ty TNHH GHI",
        "nguoi_quan_ly": "Phạm Văn D",
        "chuan_ga": "BT50",
        "loai_kep": "Đầu khoan",
        "chieu_dai_lam_viec": 130,
        "duong_kinh_kep_max": 13,
        "gia_tri_mua": 6500000,
        "chu_ky_kiem_tra": "1 năm / lần",
        "cv": 8.0,
        "dx": 8.0,
        "mon": 7,
        "tan_suat": 10,
        "ld": 110,
        "ket_luan_fuzzy": "Dùng cho các mũi khoan nhiều cỡ trên máy BT50.",
    },
    {
        "ten_thiet_bi": "Holder BT40 Tapping M6–M12",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-BT40-TAP-M6-M12",
        "ma_nha_sx": "BT40-TAP-M6-M12",
        "loai_holder": "BT40 Tapping",
        "so_serial_prefix": "SN-BT40-TAP-M6-M12",
        "nha_san_xuat": "OSG",
        "nha_cung_cap": "Công ty TNHH XYZ",
        "nguoi_quan_ly": "Trần Văn B",
        "chuan_ga": "BT40",
        "loai_kep": "Taro",
        "chieu_dai_lam_viec": 90,
        "duong_kinh_kep_max": 12,
        "gia_tri_mua": 4200000,
        "chu_ky_kiem_tra": "1 năm / lần",
        "cv": 7.0,
        "dx": 8.3,
        "mon": 9,
        "tan_suat": 20,
        "ld": 85,
        "ket_luan_fuzzy": "Chuyên dùng cho taro ren M6–M12.",
    },
    {
        "ten_thiet_bi": "Holder HSK63A dao phay ngón dài L=150",
        "nhom_thiet_bi": "Holder / Thân dao",
        "ma_noi_bo_prefix": "HLD-HSK63A-LONG-150",
        "ma_nha_sx": "HSK63A-LONG-150",
        "loai_holder": "HSK63A Extension",
        "so_serial_prefix": "SN-HSK63A-LONG-150",
        "nha_san_xuat": "SUMITOMO",
        "nha_cung_cap": "Công ty TNHH ABC",
        "nguoi_quan_ly": "Nguyễn Văn A",
        "chuan_ga": "HSK63A",
        "loai_kep": "Extension",
        "chieu_dai_lam_viec": 150,
        "duong_kinh_kep_max": 16,
        "gia_tri_mua": 8800000,
        "chu_ky_kiem_tra": "6 tháng / lần",
        "cv": 8.2,
        "dx": 8.9,
        "mon": 6,
        "tan_suat": 7,
        "ld": 150,
        "ket_luan_fuzzy": "Dùng khi cần nhô dao dài, gia công hốc sâu.",
    },
]

# 9 vị trí tủ (1 ngăn để 2 cái cùng loại)
slots = [
    ("Tủ A7", "Tầng dưới"),
    ("Tủ A8", "Tầng dưới"),
    ("Tủ A9", "Tầng dưới"),
    ("Tủ B7", "Tầng dưới"),
    ("Tủ B8", "Tầng dưới"),
    ("Tủ B9", "Tầng dưới"),
    ("Tủ C7", "Tầng dưới"),
    ("Tủ C8", "Tầng dưới"),
    ("Tủ C9", "Tầng dưới"),
]

created = 0

for idx, base in enumerate(base_types):
    tu, ngan = slots[idx]
    for i in range(1, 3):  # mỗi loại 2 cái
        ma_noi_bo = f"{base['ma_noi_bo_prefix']}-{i:02d}"

        # tránh lỗi unique nếu chạy lại nhiều lần
        if Holder.objects.filter(ma_noi_bo=ma_noi_bo).exists():
            continue

        Holder.objects.create(
            ten_thiet_bi=base["ten_thiet_bi"],
            nhom_thiet_bi=base["nhom_thiet_bi"],
            ma_noi_bo=ma_noi_bo,
            ma_nha_sx=base["ma_nha_sx"],
            loai_holder=base["loai_holder"],
            so_serial=f"{base['so_serial_prefix']}-{i:02d}",
            nha_san_xuat=base["nha_san_xuat"],
            nha_cung_cap=base["nha_cung_cap"],
            nguoi_quan_ly=base["nguoi_quan_ly"],
            trang_thai_tai_san="dang_su_dung",
            chuan_ga=base["chuan_ga"],
            loai_kep=base["loai_kep"],
            chieu_dai_lam_viec=base["chieu_dai_lam_viec"],
            duong_kinh_kep_max=base["duong_kinh_kep_max"],
            tu=tu,
            ngan=ngan,
            may_uu_tien="CNC-01, CNC-02",
            ngay_nhap_kho=date(2025, 11, 1),
            gia_tri_mua=base["gia_tri_mua"],
            chu_ky_kiem_tra=base["chu_ky_kiem_tra"],
            lan_kiem_tra_gan_nhat=None,
            so_lan_ga_thao=0,
            danh_gia_gan_nhat="",
            cv=base["cv"],
            dx=base["dx"],
            mon=base["mon"],
            tan_suat=base["tan_suat"],
            ld=base["ld"],
            ket_luan_fuzzy=base["ket_luan_fuzzy"],
        )
        created += 1

print(f"Đã tạo mới {created} Holder.")
