# Generated by Django 5.2.5 on 2025-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_holder_ma_nhom_tuong_thich_holder_tool_khuyen_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='trang_thai_tai_san',
            field=models.CharField(blank=True, choices=[('dang_su_dung', 'Đang sẵn sàng'), ('dang_bao_tri', 'Đang bảo trì'), ('ngung_su_dung', 'Ngừng sử dụng'), ('dang_duoc_muon', 'Đang được mượn')], max_length=20, null=True),
        ),
    ]
