# Generated by Django 5.2.5 on 2025-12-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0003_alter_holder_trang_thai_tai_san'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='trang_thai_tai_san',
            field=models.CharField(choices=[('san_sang', 'Sẵn sàng'), ('dang_duoc_muon', 'Đang được mượn'), ('dang_bao_tri', 'Đang bảo trì'), ('ngung_su_dung', 'Ngừng sử dụng')], default='san_sang', max_length=20),
        ),
    ]
