# Generated by Django 5.2.5 on 2025-12-25 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0004_alter_holder_trang_thai_tai_san'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='rfid',
            field=models.CharField(blank=True, db_index=True, help_text='Mã RFID của holder (UID tag), ví dụ: A1B2C3D4', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RFID chỉ gồm ký tự HEX (0-9, A-F).', regex='^[0-9A-Fa-f]+$')]),
        ),
    ]
